version: '3'
services:
  backend: &app_base
    build:
      context: .
      dockerfile: Dockerfile
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
      - node_modules-volume:/app/node_modules
      - bundle-volume:/bundle
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.6
    ports:
      - "3307:3306"
    volumes:
      - mysql-webapp-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
  # webpack-dev-server:
  #   <<: *app_base
  #   command: "bundle exec webpack-dev-server"
  #   ports:
  #    - 53036:3035
  #   tty: false
  #   stdin_open: false
volumes:
  mysql-webapp-data:
  bundle-volume:
  node_modules-volume:
